### PR TITLE
add resnap.sh

### PR DESCRIPTION
**Pull request by Evidlo**
Adds script for screenshotting reMarkable screen.

I've also updated the Wiki.  I can't make a PR, so here are the updated pages:

[Home.md](https://gist.githubusercontent.com/Evidlo/19587fef2ee285ac61ba6e37fba45a0f/raw/66e1fe2130009287c1bbe08baf20ea28789584db/rehackable-Home.md)

[resnap.sh.md](https://gist.githubusercontent.com/Evidlo/f56da243de70d98c9dc0629970564f47/raw/053d864e490024768c1e4cf770eed9371319b377/rehackable-resnap.sh.md).

### CODE REVIEW

**Comment by CTXz** [comment]
Awesome tool! I'll hopefully be able to take a closer look at this tomorrow.

**Comment by CTXz** [comment]
Sorry for the delayed response, just tested the tool. It works great, but there are two things that I've noticed.

For one, `pv` is required by your script, which at least on Ubuntu, isn't installed by default. It would be great if you could add that to the dependencies in the wiki entry.

Then, although I do get a successful image, the script exists with the following error:
```
convert-im6.q16: unexpected end-of-file `-': No such file or directory @ error/gray.c/ReadGRAYImage/218.
```

It'd be great if you could look into that as well!

**Comment by Evidlo** [comment]
`pv` is no longer a hard dependency.  I don't get that message from imagemagick on the machines iIve tested.

**Comment by CTXz** [comment]
Which version of imagemagick are you using?

**Comment by Evidlo** [comment]
Version: ImageMagick 6.9.9-38 Q16 x86_64 2018-03-12

This might be related to the change of parameters mentioned [here](https://github.com/canselcik/libremarkable/wiki/Framebuffer-Overview)?

**Comment by CTXz** [comment]
Guess that's been fixed in newer versions then, as I'm running `ImageMagick 6.9.7-4 Q16 x86_64 20170114`

I doubt that this issue is related to the change of parameters as this error occurs during run time while the raw grey image is being parsed. I have tried using `ffmpeg` as @canselcik did in the link that you've send me, which worked just fine. Additionally, ffmpeg only generates a single image on output, meaning we mustn't deal with those two black images that are being generated by imagemagick.

Would you mind if we used ffmpeg instead of imagemagick? Or is there any particular reason you chose imagemagick over ffmpeg?

**Comment by Evidlo** [comment]
I figured ImageMagick was a smaller dependency than ffmpeg.

**Comment by CTXz** [comment]
Merged after substituting imagemagick with FFmpeg and adding a few more minor changes. Wiki pages are up too.

**Pull request merged**
